server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://101.132.149.94:3306/picture-bed
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wjf159632.
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: true


